"""Sql Api V4 — main entry point.

Layered FastAPI app following the router/service/repository pattern.

- Router layer:     sql_api_v4/router.py     (HTTP endpoints)
- Service layer:    sql_api_v4/service.py    (business logic)
- Repository layer: sql_api_v4/repository.py (data access)
- Core:             core/database.py            (connection management)

Generated by Jarvis agent.
"""

import logging
from contextlib import asynccontextmanager

from fastapi import Depends, FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import RedirectResponse

from core.auth import validate_bearer_token
from core.database import DATABRICKS_HOST, DATABRICKS_HTTP_PATH
from sql_api_v4 import router as sql_api_v4_router
from catalog import router as catalog_router
from status.routers import status_router

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(application: FastAPI):
    """Validate connectivity on startup."""
    logger.info(
        "Starting Sql Api V4 — host=%s path=%s",
        DATABRICKS_HOST,
        DATABRICKS_HTTP_PATH,
    )
    yield
    logger.info("Shutting down Sql Api V4")


app = FastAPI(
    title="Sql Api V4",
    description="FastAPI app: sql-api-v4",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
async def docs_reroute() -> RedirectResponse:
    """Redirect root to API docs."""
    return RedirectResponse(url="/docs")


# Status endpoints (no auth required)
app.include_router(status_router.router, prefix="/api/v1", tags=["status"])

# Feature endpoints (token validation when APP_AUTH_MODE=token)
app.include_router(
    sql_api_v4_router.router,
    prefix="/api/v1/sql_api_v4",
    tags=["sql_api_v4"],
    dependencies=[Depends(validate_bearer_token)],
)

# Catalog scanning endpoints — Unity Catalog system.information_schema
app.include_router(
    catalog_router.router,
    prefix="/api/v1/catalog",
    tags=["catalog"],
    dependencies=[Depends(validate_bearer_token)],
)
